version: "3.8"

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    volumes:
      - .:/app
      - ./data:/data/db
    environment:
      PORT: ${PORT}
      HTTPS_PORT: ${HTTPS_PORT}
      MONGO_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - ./setup/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
